[project]
name = "econ-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "config>=0.5.1",
    "httpx>=0.28.1",
    "notebook>=7.3.3",
    "pandas>=2.2.3",
    "python-dotenv>=1.1.0",
    "requests>=2.32.3",
]
